### PR TITLE
Fix for new account exp value and workerthread overflow

### PR DESCRIPTION
**Pull request by huenato**

### CODE REVIEW

**Comment by wtfblub** [comment]
What do you mean with workerthread overflow?

**Comment by huenato** [comment]
It happened when I started the game server for the first time.
Then I changed the value of the WorkerThread field to 1 and it worked.

**Comment by wtfblub** [comment]
What cpu do you have?

**Comment by huenato** [comment]
Intel Core i3-2120

**Comment by wtfblub** [comment]
Weird. I have to look into it. -1 should be number of cpu cores * 2.

**Comment by huenato** [comment]
Then I will make a new PR for the TotalExperience missing value on account creation

**Pull request closed without merging**
