### PR TITLE
Completing P2P implementation

### PR DESCRIPTION
**Pull request by GameRaiderCC**
Fixed global p2p. (UDP enabled) (maybe not the best way, but working)

### CODE REVIEW

**Comment by BioAleks** [comment]
Is this fix this error?
https://github.com/wtfblub/NetspherePirates/issues/165

**Comment by GameRaiderCC** [comment]
I've tested it on full rooms (udp enabled) and mostly everyone(except 1) had a p2p connection.

**Comment by BioAleks** [comment]
I no use UDP. I use TCP. 
But with #165 need something do (people disconnect because of this).

Or in UDP no this problem?

**Comment by GameRaiderCC** [comment]
ProudNet's tcp has no p2p system

**Comment by BioAleks** [comment]
In last build Blub no add this. 
I have (R)(T) with udp.

**Comment by GameRaiderCC** [comment]
closed, this "workaround" isnt needed anymore

**Pull request closed without merging**
