### PR TITLE
Pbkdf2

### PR DESCRIPTION
**Pull request by Demon0no**
This replaces the current SHA1 password hashing algorithm with the way more secure PBKDF2 algorithm.
Also instead of a simple string comparison it uses crackstation.net's SlowEquals function, to eliminate possible sidechannel attacks.
Users will need to make a new account/generate new passwords though.

### CODE REVIEW

**Comment by Demon0no** [comment]
Ah, apparently I worked off the dotnetty branch instead of the master, how should this be handled?

**Comment by wtfblub** [comment]
I'll merge it when i'm done with the dotnetty branch.

**Comment by Demon0no** [comment]
I also plan to implement some of the basic features (pen rewards, room password and stuff like that) that are NYI and fix some bugs, that have open tickets. Should I do also that on top if the dotnetty branch and send a pull request so you can merge it later, or do you want me to implement/fix them on the master branch?

**Comment by wtfblub** [comment]
Work on the dotnetty branch but submit the pull request to master. Just like you did with this one.

**Comment by wtfblub** [comment]
Resubmit the pr please.

**Pull request closed without merging**
